### ISSUE TITLE
Program hangs during deviceclient.OpenAsync

### ISSUE THREAD

**Issue by pvmraghunandan** [AzureIoTGBB/azure-iot-edge-hol#7]
Following module 2, have tried to connect to edgehub using below connection string

HostName=xxxxxx;DeviceId=testdevice;SharedAccessKey=xxxxx;GatewayHostName=mygateway.local

During openAsync call the program simply hangs and is giving timeout error after sometime. Below is screenshot of edgehub logs.

![image](https://user-images.githubusercontent.com/7496232/39806357-5a79bfd8-5397-11e8-9697-8f005e421c9f.png)

Note: Haven't used cert based iotedgectl setup because doing that is giving below error from edgeHub. Instead used --auto-cert-gen-force-no-passwords

2018-05-10 01:24:33.495 +05:30 [INF] - Installing intermediate certificates.

Unhandled Exception: System.AggregateException: One or more errors occurred. (Cannot find the requested object) ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Cannot find the requested object
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] data)
   at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.CertificateHelper.<>c.<ExtractCertsFromPem>b__8_2(Byte[] c) in /opt/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/certificate/CertificateHelper.cs:line 186
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)I
   at System.Linq.Enumerable.SelectListPartitionIterator`2.MoveNext()
   at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.CertificateHelper.InstallCerts(StoreName name, StoreLocation location, IEnumerable`1 certs) in /opt/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/certificate/CertificateHelper.cs:line 162
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.<MainAsync>d__1.MoveNext() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 77
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /opt/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs:line 27

**Comment by stevebus** [comment]
sorry for the slow response.  github didn't notify me of the issue.  When you say "Haven't used cert based iotedgectl setup", you mean you didn't generate the certs and use them in the iotedgectl setup command in module 1?  if so, module 2 won't work, as the "leaf" device needs certs that it trusts to make the TLS connection to edgeHub....      as for the edgeHub cert problem.  Are you using Windows or Linux containers?
